version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://<user>:<password>@mongodb:27017/admin?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=razMp8HIKp084zP
      - MONGO_INITDB_ROOT_PASSWORD=ED1H4xLWLA40p1u
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: 