type CalendarEventType {
  id: String!
  name: String!
  startedAt: DateTimeType!
}

input CreateWalkHistoryItemType {
  latitude: Float!
  longitude: Float!
  timestamp: DateTimeType!
}

input CreateWalkHistoryType {
  history: [CreateWalkHistoryItemType!]!
}

input CreateWalkInput {
  startedAt: DateTimeType!
  finishedAt: DateTimeType!
  walkHistory: CreateWalkHistoryType!
}

"""Date with time (isoformat)"""
scalar DateTimeType

type DogType {
  id: String!
  name: String!
  breed: String!
  dateOfBirth: DateTimeType!
  sex: String!
}

input CreateDogInput {
  name: String!
  breed: String!
  dateOfBirth: DateTimeType!
  sex: String!
}

input UpdateDogInput {
  id: String!
  name: String
  breed: String
  dateOfBirth: DateTimeType
  sex: String
}

type Mutation {
  createEvent(name: String!, startedAt: DateTimeType!): CalendarEventType!
  createWalk(input: CreateWalkInput!): WalkType!
  createDog(input: CreateDogInput!): DogType!
  updateDog(input: UpdateDogInput!): DogType!
  deleteDog(id: String!): Boolean!
}

type Query {
  getEvent(id: String!): CalendarEventType
  getAllEvents: [CalendarEventType]!
  getWalks: [WalkType!]!
  getWalk(id: String!): WalkType
  getWalkDayActivity(date: DateTimeType!): WalkDayActivity!
  me: UserType!
}

type UserType {
  id: String!
  name: String!
  dogs: [DogType!]!
}

type WalkDayActivity {
  totalDistance: Float!
  totalDuration: Float!
  avgSpeed: Float!
  avgPace: Float!
  date: DateTimeType!
}

type WalkHistoryItemType {
  latitude: Float!
  longitude: Float!
  timestamp: DateTimeType!
}

type WalkHistoryType {
  history: [WalkHistoryItemType!]!
}

type WalkType {
  id: String!
  startedAt: DateTimeType!
  finishedAt: DateTimeType!
  walkHistory: WalkHistoryType!
  distance: Float!
  duration: Float!
  avgSpeed: Float!
  avgPace: Float!
}
