"""Create default user

Revision ID: bfb8d5639915
Revises: dcea7b4d0d1d
Create Date: 2025-04-28 00:28:45.142116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfb8d5639915'
down_revision: Union[str, None] = 'dcea7b4d0d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('INSERT INTO "user" (id, email, name, push_tokens, language, created_at, updated_at) VALUES (\'default_user\', \'dev@example.com\', \'Default User\', \'{}\', \'en\', NOW(), NOW())')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "user" WHERE id = \'default_user\'')
    # ### end Alembic commands ### 